apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-cashier
  labels:
    app: simple-cashier
spec:
  replicas: 4
  selector:
    matchLabels:
      app: simple-cashier
  template:
    metadata:
      labels:
        app: simple-cashier
    spec:
      containers:
        - name: simple-cashier
          image: gabrielamg/simple-cashier:1.0
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: simple-cashier-service
spec:
  type: NodePort
  selector:
    app: simple-cashier
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080